const albuns = [
    {
      title: "Fingerprints",
      year: 2026,
      genre: "Eletrônico",
      composer: "Ivan Cilento",
      coverImage: "images/fingerprints.png",
      tracks: [
        { title: "Redención", src: "media/redencion_preview.mp3", software: ["LMMS"] },
        { title: "Honorable Settlement (Syntehsis 2.0)", src: "media/honor_set_preview.mp3", software: ["LMMS"] },
        { title: "Crisp Drops", src: "media/crisp_drops_preview.mp3", software: ["MuseScore", "Audacity"] },
        { title: "The Full On", software: ["MuseScore", "Audacity"] },
        { title: "Tibetan Howl", software: ["MuseScore", "Audacity"] },
        { title: "Shivoham", software: ["LMMS"] },
        { title: "A Little More Action, please", src: "media/a_little_more_action_preview.mp3", software: ["MuseScore", "Audacity"] },
      ],
    },
    {
      title: "Winds",
      year: 2022,
      genre: "Neoclassical",
      composer: "Ivan Cilento",
      coverImage: "images/windscover.png",
      tracks: [
        { title: "A Winter Day", src: "media/awinterday_preview.mp", software: ["MuseScore"] },
        { title: "Aliseos", software: ["MuseScore"] },
        { title: "Bella Vista", src: "media/bellavista_preview.mp3", software: ["MuseScore"] },
        { title: "Into the Forest", src: "media/intotheforest_preview.mp3", software: ["MuseScore"] },
        { title: "El Niño", src: "media/nino_preview.mp3", software: ["MuseScore"] },
        { title: "La Niña", software: ["MuseScore"] },
        { title: "Storm", src: "media/storm_preview.mp3", software: ["MuseScore"] },
        { title: "Twister", software: ["MuseScore"] },
        { title: "Horse Wings", software: ["MuseScore"] },
        { title: "Fuse Breeze", src: "media/fusebreeze_preview.mp3", software: ["MuseScore"] },
        { title: "When All Becomes Powda", src: "media/whenall_preview.mp3", software: ["MuseScore"] },
        { title: "Winds", src: "media/winds_preview.mp3", software: ["MuseScore"] },
      ],
    },
    {
      title: "No Brakes",
      year: 2022,
      genre: "Electronic / Instrumental / Experimental",
      composer: "Ivan Cilento",
      coverImage: "images/nobrakes_cover.png",
      tracks: [
        { title: "Intro", software: ["MuseScore"] },
        { title: "Highway's Love", software: ["MuseScore"] },
        { title: "Roads", software: ["MuseScore"] },
        { title: "Synthesis", software: ["MuseScore"] },
        { title: "Beyond the Sky", software: ["MuseScore"] },
        { title: "Vertigo", software: ["MuseScore"] },
        { title: "An Odd March", software: ["MuseScore"] },
        { title: "Roads II", software: ["MuseScore"] },
        { title: "Presto", software: ["MuseScore"] },
        { title: "Caco Finale", software: ["MuseScore"] },
      ],
    },
  ];
  
  export default albuns;
  